"""Cascades SDK — public API client and @task/@flow DAG compiler."""

from ._meta import (
    API_CONTRACT_VERSION,
    COMPANY_NAME,
    DEFAULT_USER_AGENT,
    PRODUCT_NAME,
    SDK_MAINTAINER,
    SDK_NAME,
    SDK_REPOSITORY_URL,
    __version__,
    build_default_user_agent,
    vendor_telemetry_headers,
)

from .compiler import (
    build_dag_from_flow,
    build_dag_from_flow_json,
    canonical_json,
    canonicalize_dag,
    flow,
    task,
)

from .client import (
    Auth,
    CascadeClient,
    CascadesClient,
    CascadesSDKError,
    CascadeSDKError,
    AuthenticationError,
    CompositeAuth,
    CookieHeaderAuth,
    EngineUnavailableError,
    HeaderAuth,
    NetworkError,
    NotFoundError,
    OrchestrationError,
    RateLimitError,
    ServerError,
    SessionCookieAuth,
    TimeoutError,
    ValidationError,
    normalize_auth,
    wait_for_completion,
    wait_for_completion_async,
    wait_for_run_terminal,
    wait_for_run_terminal_async,
)

__all__ = [
    "__version__",
    "API_CONTRACT_VERSION",
    "COMPANY_NAME",
    "DEFAULT_USER_AGENT",
    "PRODUCT_NAME",
    "SDK_MAINTAINER",
    "SDK_NAME",
    "SDK_REPOSITORY_URL",
    "build_default_user_agent",
    "vendor_telemetry_headers",
    "task",
    "flow",
    "build_dag_from_flow",
    "build_dag_from_flow_json",
    "canonical_json",
    "canonicalize_dag",
    "Auth",
    "SessionCookieAuth",
    "CookieHeaderAuth",
    "HeaderAuth",
    "CompositeAuth",
    "normalize_auth",
    "CascadesClient",
    "CascadeClient",
    "wait_for_completion",
    "wait_for_completion_async",
    "wait_for_run_terminal",
    "wait_for_run_terminal_async",
    "CascadesSDKError",
    "CascadeSDKError",
    "AuthenticationError",
    "ValidationError",
    "NotFoundError",
    "RateLimitError",
    "EngineUnavailableError",
    "ServerError",
    "OrchestrationError",
    "NetworkError",
    "TimeoutError",
]
